spring:
  application:
    name: order-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        missing-queues-fatal: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha